# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PictureWindow203.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PictureWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 569)
        MainWindow.setStyleSheet("background-color: rgb(255, 220, 215);\n"
"border-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.meibai_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.meibai_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.meibai_horizontalSlider.setObjectName("meibai_horizontalSlider")
        self.gridLayout.addWidget(self.meibai_horizontalSlider, 2, 1, 1, 1)
        self.mopi_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.mopi_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mopi_horizontalSlider.setObjectName("mopi_horizontalSlider")
        self.gridLayout.addWidget(self.mopi_horizontalSlider, 1, 1, 1, 1)
        self.eye_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.eye_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.eye_pushButton.setObjectName("eye_pushButton")
        self.gridLayout.addWidget(self.eye_pushButton, 1, 2, 1, 1)
        self.saturation_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.saturation_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturation_horizontalSlider.setObjectName("saturation_horizontalSlider")
        self.gridLayout.addWidget(self.saturation_horizontalSlider, 3, 3, 1, 1)
        self.eye_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.eye_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.eye_horizontalSlider.setObjectName("eye_horizontalSlider")
        self.gridLayout.addWidget(self.eye_horizontalSlider, 1, 3, 1, 1)
        self.meimao_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.meimao_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.meimao_horizontalSlider.setObjectName("meimao_horizontalSlider")
        self.gridLayout.addWidget(self.meimao_horizontalSlider, 2, 3, 1, 1)
        self.picture_label = QtWidgets.QLabel(self.centralwidget)
        self.picture_label.setStyleSheet("background-color: rgb(255, 203, 193);\n"
"border-color: rgb(255, 255, 255);")
        self.picture_label.setText("")
        self.picture_label.setObjectName("picture_label")
        self.gridLayout.addWidget(self.picture_label, 0, 0, 1, 4)
        self.shoulian_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.shoulian_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.shoulian_pushButton.setObjectName("shoulian_pushButton")
        self.gridLayout.addWidget(self.shoulian_pushButton, 3, 0, 1, 1)
        self.shoulian_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.shoulian_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.shoulian_horizontalSlider.setObjectName("shoulian_horizontalSlider")
        self.gridLayout.addWidget(self.shoulian_horizontalSlider, 3, 1, 1, 1)
        self.mopi_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mopi_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.mopi_pushButton.setObjectName("mopi_pushButton")
        self.gridLayout.addWidget(self.mopi_pushButton, 1, 0, 1, 1)
        self.mouth_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.mouth_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.mouth_pushButton.setObjectName("mouth_pushButton")
        self.gridLayout.addWidget(self.mouth_pushButton, 4, 0, 1, 1)
        self.meimao_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.meimao_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.meimao_pushButton.setObjectName("meimao_pushButton")
        self.gridLayout.addWidget(self.meimao_pushButton, 2, 2, 1, 1)
        self.meibai_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.meibai_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.meibai_pushButton.setObjectName("meibai_pushButton")
        self.gridLayout.addWidget(self.meibai_pushButton, 2, 0, 1, 1)
        self.mouth_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.mouth_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.mouth_horizontalSlider.setObjectName("mouth_horizontalSlider")
        self.gridLayout.addWidget(self.mouth_horizontalSlider, 4, 1, 1, 1)
        self.light_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.light_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.light_pushButton.setObjectName("light_pushButton")
        self.gridLayout.addWidget(self.light_pushButton, 4, 2, 1, 1)
        self.saturation_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.saturation_pushButton.setStyleSheet("background-color: rgb(255, 195, 184);\n"
"font: 75 11pt \"爱奇艺黑体\";")
        self.saturation_pushButton.setObjectName("saturation_pushButton")
        self.gridLayout.addWidget(self.saturation_pushButton, 3, 2, 1, 1)
        self.light_horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.light_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.light_horizontalSlider.setObjectName("light_horizontalSlider")
        self.gridLayout.addWidget(self.light_horizontalSlider, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actiondelete = QtWidgets.QAction(MainWindow)
        self.actiondelete.setObjectName("actiondelete")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actiondelete)
        self.menu.addAction(self.actionsave)
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actiondelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionsave)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人像美容"))
        self.eye_pushButton.setText(_translate("MainWindow", "眼睛"))
        self.shoulian_pushButton.setText(_translate("MainWindow", "瘦脸"))
        self.mopi_pushButton.setText(_translate("MainWindow", "磨皮"))
        self.mouth_pushButton.setText(_translate("MainWindow", "红唇"))
        self.meimao_pushButton.setText(_translate("MainWindow", "鼻子"))
        self.meibai_pushButton.setText(_translate("MainWindow", "美白"))
        self.light_pushButton.setText(_translate("MainWindow", "亮度"))
        self.saturation_pushButton.setText(_translate("MainWindow", "饱和度"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "打开(&O)"))
        self.actiondelete.setText(_translate("MainWindow", "删除(&D)"))
        self.actionsave.setText(_translate("MainWindow", "保存(&S)"))
